"use client";

import { AppSidebar } from "@/components/app-sidebar";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Separator } from "@/components/ui/separator";
import Link from "next/link";

import { PostCard } from "@/components/post-card";

export default function Home() {
  // mock posts generated by ChatGPT
  const mockPosts = [
    {
      user: {
        name: "Ada Lovelace",
        avatarUrl: ""
      },
      content: "Here's a short post."
    },
    {
      user: {
        name: "Alan Turing",
        avatarUrl: ""
      },
      content: "This post is a bit longer to test how the layout adapts to different content lengths. It includes more text, more thoughts, and potentially a few line breaks if needed."
    },
    {
      user: {
        name: "Grace Hopper",
        avatarUrl: ""
      },
      content: "Here's a really long post designed to stress-test the styling and layout of the PostCard component. This post should ideally wrap across multiple lines and allow us to see how well the padding, spacing, and overall structure holds up in a more realistic usage scenario. We're simulating user-generated content of significant length here."
    }
  ];

  const mock = [ ...mockPosts, ...mockPosts, ...mockPosts ];

  return (
    <SidebarProvider>
      <AppSidebar />

      <SidebarInset>
        <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12">
          <div className="flex items-center gap-2 px-4">
            <SidebarTrigger className="-ml-1"/>
            <Separator orientation="vertical" className="mr-2 data-[orientation=vertical]:h-4"/>
            <Link href="#">Posts</Link>
          </div>
        </header>

        <div className="flex flex-1 flex-col gap-4 p-4 pt-0 items-center">
          <main className="flex flex-col gap-6 lg:w-3xl">
            {mock.map((post, idx) => (
              <PostCard key={idx} post={post} />
            ))}
          </main>
        </div>
      </SidebarInset>
    </SidebarProvider>
  )
}
